import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_deck/flutter_deck.dart';
import 'package:meetup_serverpod/shared_ui.dart';

class SerialisationProtocol extends FlutterDeckSlideWidget {
  const SerialisationProtocol()
      : super(
          configuration: const FlutterDeckSlideConfiguration(
            route: '/seralisation-protocol',
          ),
        );

  @override
  FlutterDeckSlide build(BuildContext context) {
    return FlutterDeckSlide.blank(
      builder: (context) => const SplitLayout(
        leftContent: _LeftContent(),
        rightContent: _RightContent(),
      ),
    );
  }
}

class _LeftContent extends StatelessWidget {
  const _LeftContent();

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16) * 4,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          AutoSizeText(
            'Seralisation of data - protocol',
            style: Theme.of(context).textTheme.displayLarge?.copyWith(decoration: TextDecoration.underline),
          ),
          const SizedBox(height: 32),
          AutoSizeText(
            ' • can be passed between server and client',
            style: Theme.of(context).textTheme.displayMedium,
          ),
          const SizedBox(height: 16),
          AutoSizeText(
            ' • or used to communicate with the database',
            style: Theme.of(context).textTheme.displayMedium,
          ),
          const SizedBox(height: 16),
          AutoSizeText(
            ' • defined in yaml-files in the lib/src/protocol (dart files generated by "serverpod generate")',
            style: Theme.of(context).textTheme.displayMedium,
          ),
          const SizedBox(height: 32),

          AutoSizeText(
            'Supported types',
            style: Theme.of(context).textTheme.displayMedium,
          ),
          const SizedBox(height: 16),
          AutoSizeText(
            ' • bool, int, double, String, DateTime, ByteData, List and Map',
            style: Theme.of(context).textTheme.displayMedium,
          ),
          const SizedBox(height: 16),
        ],
      ),
    );
  }
}

class _RightContent extends StatelessWidget {
  const _RightContent();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.only(right: 42.0),
      child: FlutterDeckCodeHighlight(
        code: '''class: Car
table: car
fields:
  brand: String
  model: String
  registrationDate: DateTime
  mileage: int
  value: int
        ''',
        fileName: 'car.yaml',
        language: 'yaml',
      ),
    );
  }
}
