version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cars
      POSTGRES_PASSWORD: "jzcRhPAuHKf0_vCkIYNrYOd0FsmMqEyO"
    volumes:
      - cars_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "mpaLEqnMFVEr0B7M3PVrQrU9lxtLeofH"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  cars_data:
